// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_hu

package numbertext

import _ "embed"

// Opt-in embed for the "hu" language. Build with
// -tags "numbertext_select numbertext_lang_hu" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/hu.sor
var source_hu string

func init() {
	reg.register("hu", source_hu)
}
