// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_sq

package numbertext

import _ "embed"

// Opt-in embed for the "sq" language. Build with
// -tags "numbertext_select numbertext_lang_sq" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/sq.sor
var source_sq string

func init() {
	reg.register("sq", source_sq)
}
