// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_uk

package numbertext

import _ "embed"

// Opt-in embed for the "uk" language. Build with
// -tags "numbertext_select numbertext_lang_uk" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/uk.sor
var source_uk string

func init() {
	reg.register("uk", source_uk)
}
