// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_mr

package numbertext

import _ "embed"

// Opt-in embed for the "mr" language. Build with
// -tags "numbertext_select numbertext_lang_mr" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/mr.sor
var source_mr string

func init() {
	reg.register("mr", source_mr)
}
