// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_gl

package numbertext

import _ "embed"

// Opt-in embed for the "gl" language. Build with
// -tags "numbertext_select numbertext_lang_gl" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/gl.sor
var source_gl string

func init() {
	reg.register("gl", source_gl)
}
