// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_pl

package numbertext

import _ "embed"

// Opt-in embed for the "pl" language. Build with
// -tags "numbertext_select numbertext_lang_pl" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/pl.sor
var source_pl string

func init() {
	reg.register("pl", source_pl)
}
