// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_no

package numbertext

import _ "embed"

// Opt-in embed for the "no" language. Build with
// -tags "numbertext_select numbertext_lang_no" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/no.sor
var source_no string

func init() {
	reg.register("no", source_no)
}
