// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_el

package numbertext

import _ "embed"

// Opt-in embed for the "el" language. Build with
// -tags "numbertext_select numbertext_lang_el" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/el.sor
var source_el string

func init() {
	reg.register("el", source_el)
}
