// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_tr

package numbertext

import _ "embed"

// Opt-in embed for the "tr" language. Build with
// -tags "numbertext_select numbertext_lang_tr" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/tr.sor
var source_tr string

func init() {
	reg.register("tr", source_tr)
}
