// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_ms

package numbertext

import _ "embed"

// Opt-in embed for the "ms" language. Build with
// -tags "numbertext_select numbertext_lang_ms" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/ms.sor
var source_ms string

func init() {
	reg.register("ms", source_ms)
}
