// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_lb

package numbertext

import _ "embed"

// Opt-in embed for the "lb" language. Build with
// -tags "numbertext_select numbertext_lang_lb" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/lb.sor
var source_lb string

func init() {
	reg.register("lb", source_lb)
}
