// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_bg

package numbertext

import _ "embed"

// Opt-in embed for the "bg" language. Build with
// -tags "numbertext_select numbertext_lang_bg" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/bg.sor
var source_bg string

func init() {
	reg.register("bg", source_bg)
}
