// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_fa

package numbertext

import _ "embed"

// Opt-in embed for the "fa" language. Build with
// -tags "numbertext_select numbertext_lang_fa" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/fa.sor
var source_fa string

func init() {
	reg.register("fa", source_fa)
}
