// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_hu_hung

package numbertext

import _ "embed"

// Opt-in embed for the "hu_Hung" language. Build with
// -tags "numbertext_select numbertext_lang_hu_hung" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/hu_Hung.sor
var source_hu_Hung string

func init() {
	reg.register("hu_Hung", source_hu_Hung)
}
