// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_roman

package numbertext

import _ "embed"

// Opt-in embed for the "Roman" language. Build with
// -tags "numbertext_select numbertext_lang_roman" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/Roman.sor
var source_Roman string

func init() {
	reg.register("Roman", source_Roman)
}
