// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_pt

package numbertext

import _ "embed"

// Opt-in embed for the "pt" language. Build with
// -tags "numbertext_select numbertext_lang_pt" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/pt.sor
var source_pt string

func init() {
	reg.register("pt", source_pt)
}
