// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_is

package numbertext

import _ "embed"

// Opt-in embed for the "is" language. Build with
// -tags "numbertext_select numbertext_lang_is" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/is.sor
var source_is string

func init() {
	reg.register("is", source_is)
}
