// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_he

package numbertext

import _ "embed"

// Opt-in embed for the "he" language. Build with
// -tags "numbertext_select numbertext_lang_he" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/he.sor
var source_he string

func init() {
	reg.register("he", source_he)
}
