// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_vi

package numbertext

import _ "embed"

// Opt-in embed for the "vi" language. Build with
// -tags "numbertext_select numbertext_lang_vi" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/vi.sor
var source_vi string

func init() {
	reg.register("vi", source_vi)
}
