// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_de

package numbertext

import _ "embed"

// Opt-in embed for the "de" language. Build with
// -tags "numbertext_select numbertext_lang_de" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/de.sor
var source_de string

func init() {
	reg.register("de", source_de)
}
