// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_et

package numbertext

import _ "embed"

// Opt-in embed for the "et" language. Build with
// -tags "numbertext_select numbertext_lang_et" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/et.sor
var source_et string

func init() {
	reg.register("et", source_et)
}
