// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_sl

package numbertext

import _ "embed"

// Opt-in embed for the "sl" language. Build with
// -tags "numbertext_select numbertext_lang_sl" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/sl.sor
var source_sl string

func init() {
	reg.register("sl", source_sl)
}
