// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_eo

package numbertext

import _ "embed"

// Opt-in embed for the "eo" language. Build with
// -tags "numbertext_select numbertext_lang_eo" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/eo.sor
var source_eo string

func init() {
	reg.register("eo", source_eo)
}
