// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_nl

package numbertext

import _ "embed"

// Opt-in embed for the "nl" language. Build with
// -tags "numbertext_select numbertext_lang_nl" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/nl.sor
var source_nl string

func init() {
	reg.register("nl", source_nl)
}
