// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_es

package numbertext

import _ "embed"

// Opt-in embed for the "es" language. Build with
// -tags "numbertext_select numbertext_lang_es" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/es.sor
var source_es string

func init() {
	reg.register("es", source_es)
}
