// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_fi

package numbertext

import _ "embed"

// Opt-in embed for the "fi" language. Build with
// -tags "numbertext_select numbertext_lang_fi" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/fi.sor
var source_fi string

func init() {
	reg.register("fi", source_fi)
}
