// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_lg

package numbertext

import _ "embed"

// Opt-in embed for the "lg" language. Build with
// -tags "numbertext_select numbertext_lang_lg" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/lg.sor
var source_lg string

func init() {
	reg.register("lg", source_lg)
}
