// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_cs

package numbertext

import _ "embed"

// Opt-in embed for the "cs" language. Build with
// -tags "numbertext_select numbertext_lang_cs" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/cs.sor
var source_cs string

func init() {
	reg.register("cs", source_cs)
}
