// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_af

package numbertext

import _ "embed"

// Opt-in embed for the "af" language. Build with
// -tags "numbertext_select numbertext_lang_af" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/af.sor
var source_af string

func init() {
	reg.register("af", source_af)
}
