// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_hr

package numbertext

import _ "embed"

// Opt-in embed for the "hr" language. Build with
// -tags "numbertext_select numbertext_lang_hr" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/hr.sor
var source_hr string

func init() {
	reg.register("hr", source_hr)
}
