// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_sr

package numbertext

import _ "embed"

// Opt-in embed for the "sr" language. Build with
// -tags "numbertext_select numbertext_lang_sr" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/sr.sor
var source_sr string

func init() {
	reg.register("sr", source_sr)
}
