// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_ko

package numbertext

import _ "embed"

// Opt-in embed for the "ko" language. Build with
// -tags "numbertext_select numbertext_lang_ko" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/ko.sor
var source_ko string

func init() {
	reg.register("ko", source_ko)
}
