// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_zh

package numbertext

import _ "embed"

// Opt-in embed for the "zh" language. Build with
// -tags "numbertext_select numbertext_lang_zh" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/zh.sor
var source_zh string

func init() {
	reg.register("zh", source_zh)
}
