// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_ca

package numbertext

import _ "embed"

// Opt-in embed for the "ca" language. Build with
// -tags "numbertext_select numbertext_lang_ca" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/ca.sor
var source_ca string

func init() {
	reg.register("ca", source_ca)
}
