// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_sh

package numbertext

import _ "embed"

// Opt-in embed for the "sh" language. Build with
// -tags "numbertext_select numbertext_lang_sh" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/sh.sor
var source_sh string

func init() {
	reg.register("sh", source_sh)
}
