// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_en

package numbertext

import _ "embed"

// Opt-in embed for the "en" language. Build with
// -tags "numbertext_select numbertext_lang_en" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/en.sor
var source_en string

func init() {
	reg.register("en", source_en)
}
