// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_da

package numbertext

import _ "embed"

// Opt-in embed for the "da" language. Build with
// -tags "numbertext_select numbertext_lang_da" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/da.sor
var source_da string

func init() {
	reg.register("da", source_da)
}
