// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_ga

package numbertext

import _ "embed"

// Opt-in embed for the "ga" language. Build with
// -tags "numbertext_select numbertext_lang_ga" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/ga.sor
var source_ga string

func init() {
	reg.register("ga", source_ga)
}
