// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_lv

package numbertext

import _ "embed"

// Opt-in embed for the "lv" language. Build with
// -tags "numbertext_select numbertext_lang_lv" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/lv.sor
var source_lv string

func init() {
	reg.register("lv", source_lv)
}
