// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_suzhou

package numbertext

import _ "embed"

// Opt-in embed for the "Suzhou" language. Build with
// -tags "numbertext_select numbertext_lang_suzhou" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/Suzhou.sor
var source_Suzhou string

func init() {
	reg.register("Suzhou", source_Suzhou)
}
