// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_sv

package numbertext

import _ "embed"

// Opt-in embed for the "sv" language. Build with
// -tags "numbertext_select numbertext_lang_sv" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/sv.sor
var source_sv string

func init() {
	reg.register("sv", source_sv)
}
