// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_th

package numbertext

import _ "embed"

// Opt-in embed for the "th" language. Build with
// -tags "numbertext_select numbertext_lang_th" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/th.sor
var source_th string

func init() {
	reg.register("th", source_th)
}
