// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_lt

package numbertext

import _ "embed"

// Opt-in embed for the "lt" language. Build with
// -tags "numbertext_select numbertext_lang_lt" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/lt.sor
var source_lt string

func init() {
	reg.register("lt", source_lt)
}
