// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_ru

package numbertext

import _ "embed"

// Opt-in embed for the "ru" language. Build with
// -tags "numbertext_select numbertext_lang_ru" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/ru.sor
var source_ru string

func init() {
	reg.register("ru", source_ru)
}
