// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_ja

package numbertext

import _ "embed"

// Opt-in embed for the "ja" language. Build with
// -tags "numbertext_select numbertext_lang_ja" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/ja.sor
var source_ja string

func init() {
	reg.register("ja", source_ja)
}
