#!/usr/bin/env python3
"""Generate one locale_<code>.go file per data/*.sor file.

Each generated file embeds exactly one language, guarded by a build tag
pair ("numbertext_select" plus "numbertext_lang_<code>"), so a consumer
of this module can choose to embed only a subset of languages instead of
the default (embed everything, see locale_all.go). See "Selecting which
languages get embedded" in README.md.

These files are generated, not hand-maintained: re-run this script (from
the repository root, or anywhere - it locates paths relative to itself)
whenever data/*.sor gains or loses a file, e.g. after scripts/sync-data.sh,
then re-run `gofmt -l .` and the test suite.

Usage: scripts/gen-locale-embeds.py
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, "data")

TEMPLATE = '''\
// Code generated by scripts/gen-locale-embeds.py. DO NOT EDIT.

//go:build numbertext_select && numbertext_lang_{tag}

package numbertext

import _ "embed"

// Opt-in embed for the "{code}" language. Build with
// -tags "numbertext_select numbertext_lang_{tag}" (plus one such tag per
// language you want) to embed only a chosen subset instead of every
// bundled language — see "Selecting which languages get embedded" in
// README.md.
//
//go:embed data/{filename}
var source_{ident} string

func init() {{
	reg.register("{code}", source_{ident})
}}
'''


def sanitize(code: str) -> str:
    return re.sub(r"[^0-9A-Za-z_]", "_", code)


def main() -> int:
    if not os.path.isdir(DATA_DIR):
        print(f"data directory not found: {DATA_DIR}", file=sys.stderr)
        return 1

    files = sorted(f for f in os.listdir(DATA_DIR) if f.endswith(".sor"))
    if not files:
        print(f"no .sor files found in {DATA_DIR}", file=sys.stderr)
        return 1

    # Remove previously generated files so a locale removed from data/
    # doesn't leave a stale embed behind. Only ever touch files this
    # script itself produced (marked by the "Code generated" header) -
    # never locale_all.go, which is hand-written and matches the same
    # naming shape by coincidence ("all" is not a data/*.sor code).
    marker = "// Code generated by scripts/gen-locale-embeds.py."
    for name in os.listdir(ROOT):
        if not re.match(r"^locale_[0-9a-z_]+\.go$", name):
            continue
        path = os.path.join(ROOT, name)
        with open(path, encoding="utf-8") as f:
            first_line = f.readline()
        if first_line.startswith(marker):
            os.remove(path)

    for fname in files:
        code = fname[:-len(".sor")]
        ident = sanitize(code)
        tag = ident.lower()
        content = TEMPLATE.format(tag=tag, code=code, filename=fname, ident=ident)
        out_path = os.path.join(ROOT, f"locale_{tag}.go")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)

    print(f"generated {len(files)} locale_<code>.go files in {ROOT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
